# Generated by Django 4.1.5 on 2023-01-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_востребованность_география_навыки_последние'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feature',
            new_name='Home',
        ),
    ]
