# Generated by Django 4.1.5 on 2023-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_feature_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='d2',
            field=models.CharField(default='d1', max_length=500),
        ),
    ]
