# Generated by Django 4.1.5 on 2023-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_home_d2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='details',
            new_name='d1',
        ),
        migrations.AddField(
            model_name='home',
            name='d3',
            field=models.CharField(default='d2', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='d4',
            field=models.CharField(default='d3', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='d5',
            field=models.CharField(default='d4', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='d6',
            field=models.CharField(default='d5', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='d7',
            field=models.CharField(default='d6', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='d8',
            field=models.CharField(default='d7', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='d9',
            field=models.CharField(default='d8', max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='d2',
            field=models.CharField(default='d2', max_length=500),
        ),
    ]
