# Generated by Django 4.1.5 on 2023-01-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_details_home_d1_home_d3_home_d4_home_d5_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='datahome',
        ),
    ]
