# Generated by Django 4.1.5 on 2023-01-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_home_datahome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Навыки',
            new_name='Востребованно',
        ),
        migrations.RenameModel(
            old_name='Востребованность',
            new_name='Географ',
        ),
        migrations.RenameModel(
            old_name='Последние',
            new_name='Навык',
        ),
        migrations.RenameModel(
            old_name='География',
            new_name='Послед',
        ),
    ]
