# Generated by Django 4.1.5 on 2023-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_навыки_востребованно_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feauters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('d1', models.CharField(max_length=500)),
                ('d2', models.CharField(default='', max_length=500)),
                ('d3', models.CharField(default='', max_length=500)),
                ('d4', models.CharField(default='', max_length=500)),
                ('d5', models.CharField(default='', max_length=500)),
                ('d6', models.CharField(default='', max_length=500)),
                ('d7', models.CharField(default='', max_length=500)),
                ('d8', models.CharField(default='', max_length=500)),
                ('d9', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('d1', models.CharField(max_length=500)),
                ('d2', models.CharField(default='', max_length=500)),
                ('d3', models.CharField(default='', max_length=500)),
                ('d4', models.CharField(default='', max_length=500)),
                ('d5', models.CharField(default='', max_length=500)),
                ('d6', models.CharField(default='', max_length=500)),
                ('d7', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='datahome',
        ),
    ]
