# Generated by Django 4.1.5 on 2023-01-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_feauters_fields_delete_datahome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fields',
        ),
    ]
