# Generated by Django 4.1.5 on 2023-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='востребованно',
            name='specifications',
            field=models.FileField(default='', upload_to='router_specifications'),
        ),
    ]
