# Generated by Django 4.1.5 on 2023-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_востребованно_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='востребованно',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='востребованно',
            name='profile',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
