# Generated by Django 4.1.5 on 2023-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_востребованно_image_востребованно_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='востребованно',
            old_name='profile',
            new_name='for_files',
        ),
        migrations.RenameField(
            model_name='востребованно',
            old_name='image',
            new_name='for_images',
        ),
        migrations.RemoveField(
            model_name='востребованно',
            name='details',
        ),
        migrations.RemoveField(
            model_name='востребованно',
            name='name',
        ),
        migrations.RemoveField(
            model_name='востребованно',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='географ',
            name='details',
        ),
        migrations.RemoveField(
            model_name='географ',
            name='name',
        ),
        migrations.AddField(
            model_name='географ',
            name='for_files',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AddField(
            model_name='географ',
            name='for_images',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
