# Generated by Django 4.1.5 on 2023-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_profile_востребованно_for_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='d8',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='d9',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='востребованно',
            name='for_files',
            field=models.FileField(default=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='востребованно',
            name='for_images',
            field=models.ImageField(default=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='географ',
            name='for_files',
            field=models.FileField(default=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='географ',
            name='for_images',
            field=models.ImageField(default=True, upload_to='images'),
        ),
    ]
