# Generated by Django 4.1.5 on 2023-01-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_fields_d8_alter_fields_d9_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='d8',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='d9',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='востребованно',
            name='for_files',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='востребованно',
            name='for_images',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='географ',
            name='for_files',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='географ',
            name='for_images',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
