# Generated by Django 4.1.5 on 2023-01-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_fields_d8_alter_fields_d9_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='географ',
            name='for_files',
        ),
        migrations.RemoveField(
            model_name='географ',
            name='for_images',
        ),
        migrations.AddField(
            model_name='географ',
            name='files',
            field=models.FileField(default='', upload_to='file'),
        ),
        migrations.AddField(
            model_name='географ',
            name='images',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
